/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckRouteImport } from './routes/check'
import { Route as HowRouteImport } from './routes/how'
import { Route as ReferenceRouteImport } from './routes/reference'
import { Route as ApiExtractClaimsRouteImport } from './routes/api/extract-claims'
import { Route as DocIdRouteImport } from './routes/doc.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckRoute = CheckRouteImport.update({
  id: '/check',
  path: '/check',
  getParentRoute: () => rootRouteImport,
} as any)
const HowRoute = HowRouteImport.update({
  id: '/how',
  path: '/how',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenceRoute = ReferenceRouteImport.update({
  id: '/reference',
  path: '/reference',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtractClaimsRoute = ApiExtractClaimsRouteImport.update({
  id: '/api/extract-claims',
  path: '/api/extract-claims',
  getParentRoute: () => rootRouteImport,
} as any)
const DocIdRoute = DocIdRouteImport.update({
  id: '/doc/$id',
  path: '/doc/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/check': typeof CheckRoute
  '/how': typeof HowRoute
  '/reference': typeof ReferenceRoute
  '/api/extract-claims': typeof ApiExtractClaimsRoute
  '/doc/$id': typeof DocIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/check': typeof CheckRoute
  '/how': typeof HowRoute
  '/reference': typeof ReferenceRoute
  '/api/extract-claims': typeof ApiExtractClaimsRoute
  '/doc/$id': typeof DocIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/check': typeof CheckRoute
  '/how': typeof HowRoute
  '/reference': typeof ReferenceRoute
  '/api/extract-claims': typeof ApiExtractClaimsRoute
  '/doc/$id': typeof DocIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/check' | '/how' | '/reference' | '/api/extract-claims' | '/doc/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/check' | '/how' | '/reference' | '/api/extract-claims' | '/doc/$id'
  id:
    | '__root__'
    | '/'
    | '/check'
    | '/how'
    | '/reference'
    | '/api/extract-claims'
    | '/doc/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckRoute: typeof CheckRoute
  HowRoute: typeof HowRoute
  ReferenceRoute: typeof ReferenceRoute
  ApiExtractClaimsRoute: typeof ApiExtractClaimsRoute
  DocIdRoute: typeof DocIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check': {
      id: '/check'
      path: '/check'
      fullPath: '/check'
      preLoaderRoute: typeof CheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how': {
      id: '/how'
      path: '/how'
      fullPath: '/how'
      preLoaderRoute: typeof HowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference': {
      id: '/reference'
      path: '/reference'
      fullPath: '/reference'
      preLoaderRoute: typeof ReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extract-claims': {
      id: '/api/extract-claims'
      path: '/api/extract-claims'
      fullPath: '/api/extract-claims'
      preLoaderRoute: typeof ApiExtractClaimsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doc/$id': {
      id: '/doc/$id'
      path: '/doc/$id'
      fullPath: '/doc/$id'
      preLoaderRoute: typeof DocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckRoute: CheckRoute,
  HowRoute: HowRoute,
  ReferenceRoute: ReferenceRoute,
  ApiExtractClaimsRoute: ApiExtractClaimsRoute,
  DocIdRoute: DocIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
